-- ============================================================
-- V2: Seed classic DSA problems
-- Note: This now only inserts problems NOT covered by V7 A2Z data
-- V7 handles: Basics, Sorting, Arrays, Binary Search, Strings, Linked List
-- This covers: HashMaps, Two Pointers, Sliding Window, Stacks, Trees, Graphs, DP, etc.
-- ============================================================

INSERT INTO problems (id, title, slug, difficulty, topic, step_number, section_name, sub_topic, pattern_tags, step_order, video_solution_url, article_solution_url, description, constraints_text, examples, hints, solution_code, solution_explanation, time_complexity, space_complexity, is_active, created_at) VALUES

-- HASHMAPS (Not in V7)
(UUID(), 'Top K Frequent Elements', 'top-k-frequent-elements', 'MEDIUM', 'HashMaps & Sets', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an integer array nums and an integer k, return the k most frequent elements.', '1 <= nums.length <= 10^5, k is in the range [1, number of unique elements]', '[{"input": "nums = [1,1,1,2,2,3], k = 2", "output": "[1,2]"}]', '["Build frequency map with HashMap", "Use bucket sort (index = frequency) for O(n)", "Or use a min-heap of size k"]', 'class Solution { public int[] topKFrequent(int[] nums, int k) { Map<Integer,Integer> freq=new HashMap<>(); for(int n:nums) freq.merge(n,1,Integer::sum); List<Integer>[] bucket=new List[nums.length+1]; freq.forEach((n,f)->{ if(bucket[f]==null) bucket[f]=new ArrayList<>(); bucket[f].add(n); }); int[] res=new int[k]; int idx=0; for(int i=bucket.length-1;i>=0&&idx<k;i--) if(bucket[i]!=null) for(int n:bucket[i]) if(idx<k) res[idx++]=n; return res; } }', 'Bucket sort by frequency: array of size n+1 where index = frequency. Scan from end for top K. O(n).', 'O(n)', 'O(n)', TRUE, NOW()),

-- TWO POINTERS
(UUID(), '3Sum', 'three-sum', 'MEDIUM', 'Two Pointers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j != k and nums[i] + nums[j] + nums[k] == 0.', '3 <= nums.length <= 3000', '[{"input": "nums = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]"}]', '["Sort the array first", "Fix one element, use two pointers for the other two", "Skip duplicates carefully"]', 'class Solution { public List<List<Integer>> threeSum(int[] nums) { Arrays.sort(nums); List<List<Integer>> res=new ArrayList<>(); for(int i=0;i<nums.length-2;i++){ if(i>0&&nums[i]==nums[i-1]) continue; int l=i+1,r=nums.length-1; while(l<r){ int sum=nums[i]+nums[l]+nums[r]; if(sum==0){ res.add(Arrays.asList(nums[i],nums[l],nums[r])); while(l<r&&nums[l]==nums[l+1]) l++; while(l<r&&nums[r]==nums[r-1]) r--; l++;r--; }else if(sum<0) l++; else r--; } } return res; } }', 'Sort, fix i, two-pointer for remaining two. Skip duplicates at each pointer.', 'O(n²)', 'O(log n)', TRUE, NOW()),

-- SLIDING WINDOW
(UUID(), 'Minimum Window Substring', 'minimum-window-substring', 'HARD', 'Sliding Window', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given two strings s and t, return the minimum window substring of s such that every character in t is included.', '1 <= s.length, t.length <= 10^5', '[{"input": "s = ADOBECODEBANC, t = ABC", "output": "BANC"}]', '["Use frequency map for t", "Expand right until window contains all chars of t", "Shrink left to minimize window"]', 'class Solution { public String minWindow(String s, String t) { Map<Character,Integer> need=new HashMap<>(); for(char c:t.toCharArray()) need.merge(c,1,Integer::sum); int l=0,have=0,want=need.size(),minL=0,minR=Integer.MAX_VALUE; Map<Character,Integer> window=new HashMap<>(); for(int r=0;r<s.length();r++){ char c=s.charAt(r); window.merge(c,1,Integer::sum); if(need.containsKey(c)&&window.get(c).equals(need.get(c))) have++; while(have==want){ if(r-l<minR-minL){minL=l;minR=r;} char lc=s.charAt(l); window.merge(lc,-1,Integer::sum); if(need.containsKey(lc)&&window.get(lc)<need.get(lc)) have--; l++; } } return minR==Integer.MAX_VALUE?"":s.substring(minL,minR+1); } }', 'Sliding window with two frequency maps. Expand right, shrink left when all chars satisfied.', 'O(|s|+|t|)', 'O(|s|+|t|)', TRUE, NOW()),

(UUID(), 'Maximum Sum Subarray of Size K', 'max-sum-subarray-size-k', 'EASY', 'Sliding Window', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an array of integers and a number k, find the maximum sum of a contiguous subarray of size k.', '1 <= k <= nums.length <= 10^5', '[{"input": "nums = [2,1,5,1,3,2], k = 3", "output": "9", "explanation": "Subarray [5,1,3]"}]', '["Compute sum of first k elements", "Slide the window: add next element, remove first element", "Track maximum sum"]', 'class Solution { public int maxSumSubarray(int[] nums, int k) { int sum=0; for(int i=0;i<k;i++) sum+=nums[i]; int max=sum; for(int i=k;i<nums.length;i++){ sum+=nums[i]-nums[i-k]; max=Math.max(max,sum); } return max; } }', 'Fixed sliding window of size k. O(n) with running sum.', 'O(n)', 'O(1)', TRUE, NOW()),

-- LINKED LISTS (Not in V7)
(UUID(), 'LRU Cache', 'lru-cache', 'MEDIUM', 'Linked Lists', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Design a data structure that follows the Least Recently Used (LRU) cache constraint with O(1) get and put.', '1 <= capacity <= 3000, 0 <= key, value <= 10^4', '[{"input": "[LRUCache,put,put,get,put,get,put,get,get,get] [[2],[1,1],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]", "output": "[null,null,null,1,null,-1,null,-1,3,4]"}]', '["Use HashMap for O(1) access", "Use doubly linked list to maintain order", "Head = most recent, Tail = least recent", "On access: move node to head"]', 'class LRUCache { private final int cap; private final Map<Integer,Node> map=new HashMap<>(); private final Node head=new Node(0,0), tail=new Node(0,0); public LRUCache(int capacity){ cap=capacity; head.next=tail; tail.prev=head; } public int get(int key){ Node n=map.get(key); if(n==null) return -1; remove(n); insertFront(n); return n.val; } public void put(int key, int value){ if(map.containsKey(key)) remove(map.get(key)); Node n=new Node(key,value); insertFront(n); map.put(key,n); if(map.size()>cap){Node lru=tail.prev; remove(lru); map.remove(lru.key);} } void remove(Node n){n.prev.next=n.next;n.next.prev=n.prev;} void insertFront(Node n){n.next=head.next;n.prev=head;head.next.prev=n;head.next=n;} class Node{int key,val;Node prev,next;Node(int k,int v){key=k;val=v;}} }', 'HashMap for O(1) lookup. Doubly linked list maintains order. Move accessed node to front, evict from tail.', 'O(1)', 'O(capacity)', TRUE, NOW()),

-- STACKS & QUEUES
(UUID(), 'Valid Parentheses', 'valid-parentheses', 'EASY', 'Stacks & Queues', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given a string s containing just the characters (), {}, [] and [], determine if the input string is valid.', '1 <= s.length <= 10^4', '[{"input": "s = ()[]{}", "output": "true"}, {"input": "s = (]", "output": "false"}]', '["Use a stack", "Push opening brackets", "On closing bracket, check stack top matches", "Valid if stack empty at end"]', 'class Solution { public boolean isValid(String s) { Deque<Character> stack=new ArrayDeque<>(); for(char c:s.toCharArray()){ if(c==''('') stack.push('')''); else if(c==''['') stack.push('']''); else if(c==''{'') stack.push(''}''); else if(stack.isEmpty()||stack.pop()!=c) return false; } return stack.isEmpty(); } }', 'Stack: push expected closing bracket for each open bracket. On close, pop and compare.', 'O(n)', 'O(n)', TRUE, NOW()),

(UUID(), 'Daily Temperatures', 'daily-temperatures', 'MEDIUM', 'Stacks & Queues', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an array of daily temperatures, return an array answer where answer[i] is the number of days until a warmer temperature.', '1 <= temperatures.length <= 10^5, 30 <= temperatures[i] <= 100', '[{"input": "temperatures = [73,74,75,71,69,72,76,73]", "output": "[1,1,4,2,1,1,0,0]"}]', '["Use a monotonic decreasing stack", "Store indices in the stack", "When current temp > stack top, pop and calculate days"]', 'class Solution { public int[] dailyTemperatures(int[] t) { int n=t.length; int[] res=new int[n]; Deque<Integer> stack=new ArrayDeque<>(); for(int i=0;i<n;i++){ while(!stack.isEmpty()&&t[i]>t[stack.peek()]){ int j=stack.pop(); res[j]=i-j; } stack.push(i); } return res; } }', 'Monotonic stack stores indices. When we find a warmer day, pop and record the difference.', 'O(n)', 'O(n)', TRUE, NOW()),

-- TREES (Not in V7)
(UUID(), 'Invert Binary Tree', 'invert-binary-tree', 'EASY', 'Trees - BFS/DFS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given the root of a binary tree, invert the tree, and return its root.', '0 <= number of nodes <= 100', '[{"input": "root = [4,2,7,1,3,6,9]", "output": "[4,7,2,9,6,3,1]"}]', '["Recursively swap left and right children", "Base case: null node"]', 'class Solution { public TreeNode invertTree(TreeNode root) { if(root==null) return null; TreeNode tmp=root.left; root.left=invertTree(root.right); root.right=invertTree(tmp); return root; } }', 'DFS post-order: recursively invert subtrees, then swap.', 'O(n)', 'O(h)', TRUE, NOW()),

(UUID(), 'Maximum Depth of Binary Tree', 'max-depth-binary-tree', 'EASY', 'Trees - BFS/DFS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given the root of a binary tree, return its maximum depth.', '0 <= number of nodes <= 10^4', '[{"input": "root = [3,9,20,null,null,15,7]", "output": "3"}]', '["DFS: return 1 + max(left depth, right depth)", "BFS: count levels"]', 'class Solution { public int maxDepth(TreeNode root) { if(root==null) return 0; return 1+Math.max(maxDepth(root.left),maxDepth(root.right)); } }', 'DFS recursion: depth = 1 + max depth of children.', 'O(n)', 'O(h)', TRUE, NOW()),

(UUID(), 'Level Order Traversal', 'binary-tree-level-order', 'MEDIUM', 'Trees - BFS/DFS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given the root of a binary tree, return the level order traversal of its nodes values.', '0 <= number of nodes <= 2000', '[{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]"}]', '["Use a queue for BFS", "Process all nodes at current level before moving to next", "Track level size at start of each iteration"]', 'class Solution { public List<List<Integer>> levelOrder(TreeNode root) { List<List<Integer>> res=new ArrayList<>(); if(root==null) return res; Queue<TreeNode> q=new LinkedList<>(); q.offer(root); while(!q.isEmpty()){ int size=q.size(); List<Integer> level=new ArrayList<>(); for(int i=0;i<size;i++){ TreeNode n=q.poll(); level.add(n.val); if(n.left!=null) q.offer(n.left); if(n.right!=null) q.offer(n.right); } res.add(level); } return res; } }', 'BFS with queue. Process level-by-level by snapshotting queue size at start of each level.', 'O(n)', 'O(n)', TRUE, NOW()),

(UUID(), 'Validate Binary Search Tree', 'validate-bst', 'MEDIUM', 'Trees - BFS/DFS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given the root of a binary tree, determine if it is a valid binary search tree.', '1 <= number of nodes <= 10^4', '[{"input": "root = [2,1,3]", "output": "true"}]', '["Pass min/max bounds to each recursive call", "Left subtree: max bound = current value", "Right subtree: min bound = current value"]', 'class Solution { public boolean isValidBST(TreeNode root) { return validate(root, Long.MIN_VALUE, Long.MAX_VALUE); } boolean validate(TreeNode n, long min, long max) { if(n==null) return true; if(n.val<=min||n.val>=max) return false; return validate(n.left,min,n.val)&&validate(n.right,n.val,max); } }', 'Pass bounds down recursively. Every node must be strictly between its inherited min/max.', 'O(n)', 'O(h)', TRUE, NOW()),

(UUID(), 'Lowest Common Ancestor of BST', 'lowest-common-ancestor-bst', 'MEDIUM', 'Trees - BFS/DFS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given a binary search tree and two nodes p and q, find their lowest common ancestor.', '2 <= number of nodes <= 10^5', '[{"input": "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", "output": "6"}]', '["If both p and q are less than root, go left", "If both greater, go right", "Otherwise root is the LCA"]', 'class Solution { public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) { while(root!=null){ if(p.val<root.val&&q.val<root.val) root=root.left; else if(p.val>root.val&&q.val>root.val) root=root.right; else return root; } return null; } }', 'Exploit BST property: LCA is first node where p and q split to different sides.', 'O(h)', 'O(1)', TRUE, NOW()),

(UUID(), 'Binary Tree Maximum Path Sum', 'binary-tree-max-path-sum', 'HARD', 'Trees - BFS/DFS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given the root of a binary tree, return the maximum path sum.', '1 <= number of nodes <= 3 * 10^4', '[{"input": "root = [-10,9,20,null,null,15,7]", "output": "42"}]', '["For each node, calculate max path through that node", "Max through node = node.val + max(0, left gain) + max(0, right gain)", "Track global max"]', 'class Solution { int max=Integer.MIN_VALUE; public int maxPathSum(TreeNode root) { gain(root); return max; } int gain(TreeNode n){ if(n==null) return 0; int l=Math.max(0,gain(n.left)),r=Math.max(0,gain(n.right)); max=Math.max(max,n.val+l+r); return n.val+Math.max(l,r); } }', 'Post-order DFS. At each node, gain = node.val + max(0, best child gain). Update global max with both children.', 'O(n)', 'O(h)', TRUE, NOW()),

-- GRAPHS
(UUID(), 'Number of Islands', 'number-of-islands', 'MEDIUM', 'Graphs', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an m x n 2D binary grid representing a map of 1s (land) and 0s (water), return the number of islands.', '1 <= m, n <= 300', '[{"input": "grid = [[1,1,0],[0,1,0],[0,0,1]]", "output": "2"}]', '["DFS or BFS from each unvisited land cell", "Mark all connected land as visited (sink it to 0)", "Count how many times you start a DFS"]', 'class Solution { public int numIslands(char[][] g) { int count=0; for(int i=0;i<g.length;i++) for(int j=0;j<g[0].length;j++) if(g[i][j]==''1''){dfs(g,i,j);count++;} return count; } void dfs(char[][] g,int i,int j){ if(i<0||i>=g.length||j<0||j>=g[0].length||g[i][j]!=''1'') return; g[i][j]=''0''; dfs(g,i+1,j);dfs(g,i-1,j);dfs(g,i,j+1);dfs(g,i,j-1); } }', 'DFS flood fill. Sink connected land to ''0'' to avoid revisiting. Count sinks = islands.', 'O(m×n)', 'O(m×n)', TRUE, NOW()),

(UUID(), 'Clone Graph', 'clone-graph', 'MEDIUM', 'Graphs', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given a reference of a node in a connected undirected graph, return a deep copy of the graph.', '1 <= number of nodes <= 100', '[{"input": "adjList = [[2,4],[1,3],[2,4],[1,3]]", "output": "[[2,4],[1,3],[2,4],[1,3]]"}]', '["Use HashMap to map original node to clone", "DFS: clone each neighbor recursively", "Base case: node already cloned"]', 'class Solution { Map<Node,Node> map=new HashMap<>(); public Node cloneGraph(Node node) { if(node==null) return null; if(map.containsKey(node)) return map.get(node); Node clone=new Node(node.val); map.put(node,clone); for(Node n:node.neighbors) clone.neighbors.add(cloneGraph(n)); return clone; } }', 'DFS with memoization map. Clone node first (before neighbours) to handle cycles.', 'O(V+E)', 'O(V)', TRUE, NOW()),

(UUID(), 'Course Schedule', 'course-schedule', 'MEDIUM', 'Graphs', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'There are numCourses courses labeled 0 to numCourses-1. Given prerequisites, determine if all courses can be finished.', '1 <= numCourses <= 2000', '[{"input": "numCourses = 2, prerequisites = [[1,0]]", "output": "true"}]', '["Model as directed graph", "Detect cycle using DFS with 3 states: 0=unvisited, 1=visiting, 2=visited", "If back edge found, cycle exists"]', 'class Solution { public boolean canFinish(int n, int[][] pre) { List<List<Integer>> adj=new ArrayList<>(); for(int i=0;i<n;i++) adj.add(new ArrayList<>()); for(int[] p:pre) adj.get(p[1]).add(p[0]); int[] state=new int[n]; for(int i=0;i<n;i++) if(state[i]==0&&hasCycle(adj,state,i)) return false; return true; } boolean hasCycle(List<List<Integer>> adj,int[] s,int u){ s[u]=1; for(int v:adj.get(u)){ if(s[v]==1) return true; if(s[v]==0&&hasCycle(adj,s,v)) return true; } s[u]=2; return false; } }', 'Topological sort / cycle detection with 3-state DFS. Cycle = course dependency loop.', 'O(V+E)', 'O(V+E)', TRUE, NOW()),

-- HEAPS
(UUID(), 'Kth Largest Element in Array', 'kth-largest-element', 'MEDIUM', 'Heaps', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an integer array nums and an integer k, return the kth largest element.', '1 <= k <= nums.length <= 10^5', '[{"input": "nums = [3,2,1,5,6,4], k = 2", "output": "5"}]', '["Use a min-heap of size k", "Add elements; if heap size > k, remove smallest", "Heap top is the kth largest"]', 'class Solution { public int findKthLargest(int[] nums, int k) { PriorityQueue<Integer> pq=new PriorityQueue<>(); for(int n:nums){ pq.offer(n); if(pq.size()>k) pq.poll(); } return pq.peek(); } }', 'Min-heap of size k. After processing all elements, top of heap is the kth largest.', 'O(n log k)', 'O(k)', TRUE, NOW()),

(UUID(), 'Find Median from Data Stream', 'find-median-data-stream', 'HARD', 'Heaps', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Design a data structure that supports adding integers and finding the median at any point.', '1 <= val <= 10^5', '[{"input": "[MedianFinder,addNum,addNum,findMedian,addNum,findMedian] [[],[1],[2],[],[3],[]]", "output": "[null,null,null,1.5,null,2.0]"}]', '["Use two heaps: max-heap for lower half, min-heap for upper half", "Balance sizes so |lower| - |upper| <= 1", "Median = max of lower (odd total) or average of both tops (even)"]', 'class MedianFinder { PriorityQueue<Integer> lo=new PriorityQueue<>(Collections.reverseOrder()); PriorityQueue<Integer> hi=new PriorityQueue<>(); public void addNum(int n){ lo.offer(n); hi.offer(lo.poll()); if(lo.size()<hi.size()) lo.offer(hi.poll()); } public double findMedian(){ return lo.size()>hi.size()?lo.peek():(lo.peek()+hi.peek())/2.0; } }', 'Two heaps: max-heap (lower) and min-heap (upper). Rebalance after each insert.', 'O(log n) add, O(1) find', 'O(n)', TRUE, NOW()),

-- DYNAMIC PROGRAMMING
(UUID(), 'Climbing Stairs', 'climbing-stairs', 'EASY', 'Dynamic Programming', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'You are climbing a staircase with n steps. Each time you can climb 1 or 2 steps. How many distinct ways can you climb to the top?', '1 <= n <= 45', '[{"input": "n = 3", "output": "3", "explanation": "1+1+1, 1+2, 2+1"}]', '["This is Fibonacci: ways(n) = ways(n-1) + ways(n-2)", "Use two variables to avoid O(n) space", "Base cases: ways(1)=1, ways(2)=2"]', 'class Solution { public int climbStairs(int n) { if(n<=2) return n; int a=1,b=2; for(int i=3;i<=n;i++){int c=a+b;a=b;b=c;} return b; } }', 'Fibonacci: f(n) = f(n-1) + f(n-2). Optimise space with two variables.', 'O(n)', 'O(1)', TRUE, NOW()),

(UUID(), 'Coin Change', 'coin-change', 'MEDIUM', 'Dynamic Programming', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given coins of certain denominations and a total amount, find the fewest number of coins needed to make that amount.', '1 <= coins.length <= 12, 0 <= amount <= 10^4', '[{"input": "coins = [1,5,11], amount = 15", "output": "3"}]', '["dp[i] = min coins to make amount i", "For each amount, try each coin denomination", "dp[i] = min(dp[i], 1 + dp[i - coin])"]', 'class Solution { public int coinChange(int[] coins, int amount) { int[] dp=new int[amount+1]; Arrays.fill(dp,amount+1); dp[0]=0; for(int i=1;i<=amount;i++) for(int c:coins) if(c<=i) dp[i]=Math.min(dp[i],1+dp[i-c]); return dp[amount]>amount?-1:dp[amount]; } }', 'Bottom-up DP. dp[i] = min coins for amount i. Try each coin denomination.', 'O(amount × coins)', 'O(amount)', TRUE, NOW()),

(UUID(), 'Longest Common Subsequence', 'longest-common-subsequence', 'MEDIUM', 'Dynamic Programming', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given two strings text1 and text2, return the length of their longest common subsequence.', '1 <= text1.length, text2.length <= 1000', '[{"input": "text1 = abcde, text2 = ace", "output": "3"}]', '["Build 2D dp table where dp[i][j] = LCS of text1[0..i] and text2[0..j]", "If chars match: dp[i][j] = 1 + dp[i-1][j-1]", "Else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])"]', 'class Solution { public int longestCommonSubsequence(String t1, String t2) { int m=t1.length(),n=t2.length(); int[][] dp=new int[m+1][n+1]; for(int i=1;i<=m;i++) for(int j=1;j<=n;j++) dp[i][j]=t1.charAt(i-1)==t2.charAt(j-1)?1+dp[i-1][j-1]:Math.max(dp[i-1][j],dp[i][j-1]); return dp[m][n]; } }', 'Classic 2D DP. Match = diagonal + 1. No match = max of left/top.', 'O(m×n)', 'O(m×n)', TRUE, NOW()),

(UUID(), 'Word Break', 'word-break', 'MEDIUM', 'Dynamic Programming', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given a string s and a dictionary, return true if s can be segmented into dictionary words.', '1 <= s.length <= 300, 1 <= wordDict.length <= 1000', '[{"input": "s = leetcode, wordDict = [leet,code]", "output": "true"}]', '["dp[i] = true if s[0..i-1] can be segmented", "For each i, try all j < i where dp[j] is true", "Check if s[j..i] is in dictionary"]', 'class Solution { public boolean wordBreak(String s, List<String> dict) { Set<String> d=new HashSet<>(dict); int n=s.length(); boolean[] dp=new boolean[n+1]; dp[0]=true; for(int i=1;i<=n;i++) for(int j=0;j<i;j++) if(dp[j]&&d.contains(s.substring(j,i))){ dp[i]=true; break; } return dp[n]; } }', 'DP: dp[i] = can string s[0..i-1] be segmented. Try all split points.', 'O(n² × k)', 'O(n)', TRUE, NOW()),

(UUID(), 'House Robber', 'house-robber', 'MEDIUM', 'Dynamic Programming', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given houses with amounts, find the maximum amount you can rob without robbing adjacent houses.', '1 <= nums.length <= 100', '[{"input": "nums = [1,2,3,1]", "output": "4"}]', '["dp[i] = max rob up to house i", "dp[i] = max(dp[i-1], nums[i] + dp[i-2])", "Optimise to two variables"]', 'class Solution { public int rob(int[] nums) { int prev2=0,prev1=0; for(int n:nums){ int cur=Math.max(prev1,n+prev2); prev2=prev1; prev1=cur; } return prev1; } }', 'DP with two variables: either skip house i or rob it and skip i-1.', 'O(n)', 'O(1)', TRUE, NOW()),

-- GREEDY
(UUID(), 'Jump Game', 'jump-game', 'MEDIUM', 'Greedy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an array where each element is the max jump length from that position, determine if you can reach the last index.', '1 <= nums.length <= 3 * 10^4', '[{"input": "nums = [2,3,1,1,4]", "output": "true"}]', '["Track the maximum reachable index", "For each position, update max reach", "If current index > max reach, return false"]', 'class Solution { public boolean canJump(int[] nums) { int maxReach=0; for(int i=0;i<nums.length;i++){ if(i>maxReach) return false; maxReach=Math.max(maxReach,i+nums[i]); } return true; } }', 'Greedy: track furthest reachable index. If index exceeds reach before we get to it, impossible.', 'O(n)', 'O(1)', TRUE, NOW()),

(UUID(), 'Meeting Rooms II', 'meeting-rooms-ii', 'MEDIUM', 'Greedy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an array of meeting time intervals, find the minimum number of conference rooms required.', '1 <= intervals.length <= 10^4', '[{"input": "intervals = [[0,30],[5,10],[15,20]]", "output": "2"}]', '["Sort meetings by start time", "Use a min-heap of end times", "If new meeting starts after earliest end, reuse room; else add new room"]', 'class Solution { public int minMeetingRooms(int[][] intervals) { Arrays.sort(intervals,(a,b)->a[0]-b[0]); PriorityQueue<Integer> pq=new PriorityQueue<>(); for(int[] i:intervals){ if(!pq.isEmpty()&&pq.peek()<=i[0]) pq.poll(); pq.offer(i[1]); } return pq.size(); } }', 'Sort by start. Min-heap tracks earliest ending room. Reuse if meeting starts after/at heap top.', 'O(n log n)', 'O(n)', TRUE, NOW()),

-- BACKTRACKING
(UUID(), 'Subsets', 'subsets', 'MEDIUM', 'Backtracking', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an integer array nums of unique elements, return all possible subsets.', '1 <= nums.length <= 10, -10 <= nums[i] <= 10', '[{"input": "nums = [1,2,3]", "output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"}]', '["Backtracking: at each step, decide to include or exclude current element", "Or iterate: for each new element, add it to all existing subsets"]', 'class Solution { public List<List<Integer>> subsets(int[] nums) { List<List<Integer>> res=new ArrayList<>(); backtrack(res,new ArrayList<>(),nums,0); return res; } void backtrack(List<List<Integer>> res, List<Integer> curr, int[] nums, int start){ res.add(new ArrayList<>(curr)); for(int i=start;i<nums.length;i++){ curr.add(nums[i]); backtrack(res,curr,nums,i+1); curr.remove(curr.size()-1); } } }', 'Backtracking: at each step, add current element and recurse, then remove (backtrack).', 'O(2^n)', 'O(n)', TRUE, NOW()),

(UUID(), 'Combination Sum', 'combination-sum', 'MEDIUM', 'Backtracking', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given a list of candidates and a target, find all unique combinations that sum to target.', '1 <= candidates.length <= 30', '[{"input": "candidates = [2,3,6,7], target = 7", "output": "[[2,2,3],[7]]"}]', '["Backtrack: try each candidate from current index", "Subtract candidate from target", "Base case: target == 0 → add to result"]', 'class Solution { public List<List<Integer>> combinationSum(int[] c, int t) { List<List<Integer>> res=new ArrayList<>(); backtrack(res,new ArrayList<>(),c,t,0); return res; } void backtrack(List<List<Integer>> res,List<Integer> curr,int[] c,int remain,int start){ if(remain==0){res.add(new ArrayList<>(curr));return;} for(int i=start;i<c.length;i++){ if(c[i]<=remain){ curr.add(c[i]); backtrack(res,curr,c,remain-c[i],i); curr.remove(curr.size()-1); } } } }', 'Backtracking with pruning. Start index prevents duplicate combinations. Reuse same element.', 'O(n^(t/min))', 'O(t/min)', TRUE, NOW()),

(UUID(), 'Permutations', 'permutations', 'MEDIUM', 'Backtracking', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Given an array nums of distinct integers, return all possible permutations.', '1 <= nums.length <= 6', '[{"input": "nums = [1,2,3]", "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}]', '["Use backtracking with a visited boolean array", "At each position, try all unvisited elements", "Backtrack by marking unvisited"]', 'class Solution { public List<List<Integer>> permute(int[] nums) { List<List<Integer>> res=new ArrayList<>(); backtrack(res,new ArrayList<>(),nums,new boolean[nums.length]); return res; } void backtrack(List<List<Integer>> res,List<Integer> curr,int[] nums,boolean[] used){ if(curr.size()==nums.length){res.add(new ArrayList<>(curr));return;} for(int i=0;i<nums.length;i++){ if(!used[i]){ used[i]=true; curr.add(nums[i]); backtrack(res,curr,nums,used); curr.remove(curr.size()-1); used[i]=false; } } } }', 'Backtracking with boolean used[] array. Try each unused element at each position.', 'O(n!)', 'O(n)', TRUE, NOW());
